### ISSUE TITLE
[BUG]: All icons need transforming

### ISSUE THREAD

**Issue by weepy** [shinokada/svelte-lucide#1]
### Description of the bug

using sveltekit's "npm build" - all the icons need transforming - even if not used.
node_modules/.pnpm/lucide-svelte@0.252.0_svelte@3.59.2/node_modules/lucide-svelte/dist/svelte/icons/venetian-mask.svelte

Very slow of course, but also cause the builder to run out of memory :(

### Steps To Reproduce

npm run build

**Comment by weepy** [comment]
oh doh - seems that this is the wrong package! not "lucide-svelte" !

**Comment by shinokada** [comment]
Using Svelte-Lucide, you can import individually. Please read [this doc](https://svelte-lucide.codewithshin.com/?id=faster-compiling).
