### ISSUE TITLE
[FEAT]: rotate prop

### ISSUE THREAD

**Issue by weepy** [shinokada/svelte-lucide#3]
### Description

it would be nice to be able to easily rotate / reflect the icons via a prop.

**Comment by shinokada** [comment]
Can you try using tailwind CSS, `class="rotate-45"`?

**Comment by weepy** [comment]
I could but I'm not using tailwind :-/ 
I suppose I could pass in a "style" ?

**Comment by shinokada** [comment]
I close the issue for now. Feel free to open a new issue.
